languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "léon h"
copyright = "Licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"

[params]
dateFormat = "2 January 2006"

[params.author]
name = "léon h"
image = "img/author.jpg"
# headline = "I'm only human"
bio = "Software engineer, former architect (as in, buildings)."
links = [
  { email = "mailto:hello@leonh.fr" },
  { github = "https://github.com/leonhfr" },
  { linkedin = "https://linkedin.com/in/leonhollender" },
]
