name: Discussions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  discussions:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch discussions
        uses: leonhfr/discussions-action@release
        with:
          apify_token: ${{ secrets.APIFY_TOKEN }}
          domain_name: leonh.fr
          target_dir: /data

      - name: Update discussions
        id: auto-commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update discussions'

      - name: Trigger deployment
        if: steps.auto-commit.outputs.changes_detected == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deployment.yaml',
              ref: 'master'
            })
